### ISSUE TITLE
Ajouter les boutons lorsque l'on clique sur "nouvelle recherche"

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/ScoreBot#2]
Lorsqu'on lance une nouvelle recherche à la fin d'une séquence, il faudrait ajouter les boutons
![image](https://github.com/philharmoniedeparis/ScoreBot/assets/10194536/3f612535-799e-4c17-bc53-d95038452d43)

**Comment by tristandeborde** [comment]
Merci, effectivement c'est beaucoup plus facile comme ça! 
Comme pour les 2 autres issues, c'est implémenté dans [le dernier commit](https://github.com/philharmoniedeparis/ScoreBot/commit/9e64197d867999e2924504bffde511471219a722).
C'est live et testable sur la [version dev du chatbot](https://rasa-x2.uat.iumio.fr/guest/conversations/production/54a4e4709e7c40c7bc6fc0ebefb01e13).

**Comment by tristandeborde** [comment]
Effectivement c'était un oubli de ma part :)
C'est corrigé.
