### ISSUE TITLE
Enlever le "s" à résultats quand on a un seul résultat

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/ScoreBot#4]
pour tester, poser la question : "je cherche une partition pour 2 flûtes et un piano du 19ème siècle"

**Comment by tristandeborde** [comment]
Merci pour la proposition! Implémenté dans [le dernier commit](https://github.com/philharmoniedeparis/ScoreBot/commit/9e64197d867999e2924504bffde511471219a722).
C'est live et testable sur la [version dev du chatbot](https://rasa-x2.uat.iumio.fr/guest/conversations/production/54a4e4709e7c40c7bc6fc0ebefb01e13).
