### ISSUE TITLE
Afficher les résultats directement si le nombre de résultats est inférieur à 15

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/ScoreBot#5]
C'est-à-dire : 

Dans tous les cas, si le nombre de résultats est inférieur à 15:

- Afficher directement les résultats
- Ne pas proposer d'affiner
- Proposer d'effectuer une nouvelle recherche

**Comment by tristandeborde** [comment]
Merci pour la proposition! Implémenté dans [le dernier commit](https://github.com/philharmoniedeparis/ScoreBot/commit/9e64197d867999e2924504bffde511471219a722).
C'est live et testable sur la [version dev du chatbot](https://rasa-x2.uat.iumio.fr/guest/conversations/production/54a4e4709e7c40c7bc6fc0ebefb01e13).
