### ISSUE TITLE
Manque le bouton "consulter les résultats"

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/ScoreBot#7]
Dans le cas ci-dessous :
![image](https://github.com/philharmoniedeparis/ScoreBot/assets/10194536/fd573dc3-ab96-4535-854b-ea151f86c55b)
On m'a proposé d'affiner par Niveau, ce que j'ai demandé, mais alors on me dit que les niveaux n'ont pas pu être récupérés (c'est un premier problème car on m'a proposé d'affiner par niveau) puis on me propose d'afficher les résultats, mais je n'ai plus le bouton pour le faire.

**Comment by rbailly** [comment]
Même problème ici:
![image](https://github.com/philharmoniedeparis/ScoreBot/assets/10194536/b3114bae-9472-4249-8fa7-c941f061293c)

**Comment by tristandeborde** [comment]
C'est corrigé! merci pour le retour
